name: Unit Testing & UI Testing

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["main"]

jobs:
    build_and_test:
        runs-on: macos-15

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup iOS Simulator
          uses: futureware-tech/simulator-action@v4
          with:
            model: 'iPhone 16'

        - name: Run Tests
          run: |
            xcodebuild test \
            -scheme Bangunin \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            clean test | xcpretty

